name: tagmine_api
description: Tagmine Dart OAS client generator
version: 1.0.0
repository: https://github.com/nexushunter/tagmine-api

environment:
  sdk: ^3.0.5

dependencies:
  dio: ^5.0.0
  openapi_generator_annotations: ^4.12.0
  build_runner: any
  built_value: any
  openapi_generator: ^4.12.0
  logging: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0