name: 'Release'

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: infrastructure

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: 'Upload OAS Spec'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: true
          terraform_version: 1.5.5
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve